Array exercise complited
NickelGit/study pull request #1
Opened 2020-04-22 06:49 UTC by NickelGit

Введение в программирование Ruby/JS >> Массивы

2020-04-22 08:28 UTC, devality commented
Нужно разкомментировать тесты и убедиться что они проходят.

2020-04-22 08:36 UTC, NickelGit commented
> 
> 
> Нужно разкомментировать тесты и убедиться что они проходят.

На локальной машине разкоментил и протестил все, но измененный test.rb не коммитил. Надо его тоже закомитить и запушить?

2020-04-22 08:49 UTC, devality commented
Да, в корне проекта лежит `.travis.yml` этот файл позволяет гитхабу интегрироваться с тревисом, сервисом для прогона тестов, и отображать статусы тестов напротив каждого коммита прямо на гитхабе.

2020-04-22 08:56 UTC, devality requested changes

2020-04-22 08:56 UTC, devality commented on test/exercise/arrays/solution.rb
> +        max = array.max
А давай реализуем функцию `max` тоже сами.

2020-04-22 08:56 UTC, devality commented on test/exercise/arrays/solution.rb
> +        end
Для трансформации массива прекрасно подходит функция `map`.

2020-04-22 08:56 UTC, devality commented on test/exercise/arrays/solution.rb
> +        loop do
В руби принято избегать использования циклов, код станет понятнее если тело цикла вынести в функцию и использовать ее рекурсивно.

2020-04-22 12:32 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        loop do
Пасиб за рекомендации, вродь все пофиксил. Запушил новые версии. Жмакнул заново галку на learn.Dualboot

2020-04-23 07:58 UTC, devality approved these changes

2020-04-23 09:40 UTC, merged